### ISSUE TITLE
Lab setup issues

### ISSUE THREAD

**Issue by marrober** [osevg/workshopper-content#187]
I had a few issues setting up the lab today which I thought were worth reporting :

1. Ansible could not find the roles in the locations where they are installed. I am not an ansible expert so I looked at where ansible was trying to find them and copied the roles there using these commands :

mkdir -p /opt/app-root/src/configs/ocp-workloads/roles
cp -R ./roles/* /opt/app-root/src/configs/ocp-workloads/roles

2. One of the roles has _ in the name where it should be - : ocp4-workload-nexus-operator. Once this was replaced the nexus project was created.

3. A minor thing but the project that is created is called 'lab' and the documentation currently refers to 'labs'.

Feel free to tell me to fix the above and create a pull request for you to review and accept.

**Comment by blues-man** [comment]
Hello, thanks for reporting it. The nexus module has changes in the while, it may have been renamed from `ocp4_workload_nexus_operator` to `ocp4-workload-nexus-operator`.

Yes lab(s) mismatch, thanks for reporting it. Can you send a PR with these changes and then we check internally for Nexus if the rename is enough?

Thanks!

**Comment by marrober** [comment]
Will do that early next week.

Any idea how we overcome the Roles location issue ?

**Comment by blues-man** [comment]
I have to ping @wkulhanek for that :)

**Comment by wkulhanek** [comment]
@blues-man @marrober I have no idea what this problem is...
Bottom line in AgnosticD (why is this even an issue here?) we have old roles - those are the ones with "-" in the names. And then we have newer, modern roles - the ones with Ansible compliant "_" in the name. I don't touch the old roles anymore. If they're broken I point people to the new ones.

The reason we have both.... is that we didn't want to break existing environments when be brought these roles into what is now our design/coding guidelines.
